//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.StockDatas = new HashSet<StockData>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<StockData> StockDatas { get; set; }
    }
}
