//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockData
    {
        public int CompanyID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public decimal OpenP { get; set; }
        public decimal CloseP { get; set; }
        public decimal HighP { get; set; }
        public decimal LowP { get; set; }
        public int Volumne { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
